In [46]:
##RandomForest for iris dataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score
X=load_iris().data
Y=load_iris().target
forest=RandomForestClassifier(n_estimators=100, max_depth=2,criterion='entropy',random_state=10)
forest.fit(X,Y)
yforest=forest.predict(X)
print(accuracy_score(Y,yforest))
print(forest.feature_importances_)
print(cross_val_score(forest,X,Y,cv=10).mean())

##AdaBoostClassifier on iris dataset
model=AdaBoostClassifier(DecisionTreeClassifier(max_depth=3),n_estimators=100)#default,weak learners decision stumps.
model.fit(X,Y)
ymodel=model.predict(X)
print(accuracy_score(Y,ymodel))
print(model.feature_importances_)

##BaggingClassifier on iris dataset
bag=BaggingClassifier(n_estimators=100)
bag.fit(X,Y)
ybag=bag.predict(X)
print(accuracy_score(Y,ybag))
print(model.feature_importances_)

0.96
[0.09920058 0.00273288 0.43819932 0.45986723]
0.9466666666666667
1.0
[0.1833197  0.23266284 0.21252682 0.37149063]
1.0
[0.1833197  0.23266284 0.21252682 0.37149063]


In [45]:
##make_selection dataset
from sklearn.datasets import make_gaussian_quantiles, make_classification
X,Y=make_classification(n_samples=1000, n_features=4, random_state=10, shuffle=True)
model=AdaBoostClassifier(n_estimators=100,algorithm="SAMME")
model.fit(X,Y)
print(model.score(X,Y))
model.feature_importances_

0.884


array([0.2046279 , 0.32918505, 0.45077152, 0.01541553])